#!/usr/bin/env bash
# Regenerate the `rmesh-crate` snapshot branch.
#
# WHY THIS EXISTS
# ---------------
# `rmesh` consumes this repo's Rust crate as an optional cargo dependency. Cargo
# resolves a git dependency by cloning the repo AND its submodules, before it
# knows or cares whether the feature is enabled. This repo carries `occt/` — the
# full OpenCASCADE C++ source — as a submodule, so a plain
# `git = "…/occt-wasm", rev = "…"` dependency costs every downstream consumer:
#
#     ~96 MB   occt-wasm git db
#    ~222 MB   occt submodule git db
#    ~617 MB   checkout (515 MB of which is occt/)
#    ~37 s     wall clock
#
# …at zero features, forever. Measured, not estimated.
#
# This script publishes a single-commit orphan branch holding ONLY the crate,
# promoted to the repo root, with no submodule — a ~5 MB fetch. It is a faithful
# subset: no source is edited, so reviewing the branch is reviewing a file list.
# The only change is `crate/Cargo.toml`, which must stop inheriting from the
# workspace it no longer has.
#
# The destination is a crates.io publish, where an inactive optional dependency
# costs a consumer nothing at all (an index entry, no download). This branch is
# the bridge until that lands; the kernel blob is dropped as part of that publish
# (`default-features = false` already means rmesh never compiles it in).
#
# Usage:  scripts/make-rmesh-crate.sh [branch-name]
# Then:   git push origin rmesh-crate

set -euo pipefail

BRANCH="${1:-rmesh-crate}"
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOURCE_REV="$(git -C "$REPO" rev-parse HEAD)"
SOURCE_DESC="$(git -C "$REPO" describe --always --dirty)"

staging="$(mktemp -d)"
trap 'rm -rf "$staging"' EXIT

# The crate, promoted to the root of the snapshot. Everything else in the repo
# (occt/, facade/, ts/, xtask/, test/, examples/) is build machinery for
# producing the wasm module and has no business in a cargo dependency.
cp -R "$REPO/crate/." "$staging/"

# `crate/Cargo.toml` inherits `edition`/`license`/`repository`/`rust-version`
# and its lint table from the workspace root, which the snapshot does not carry.
# Resolve those to literals. The lint table is deliberately NOT carried over:
# lints are a developer concern of this repo, and a dependency that fails a
# consumer's build over a lint level is a dependency that gets forked again.
python3 - "$REPO/Cargo.toml" "$staging/Cargo.toml" <<'PY'
import re, sys

workspace_path, crate_path = sys.argv[1], sys.argv[2]
workspace = open(workspace_path).read()
crate = open(crate_path).read()

package = re.search(r"\[workspace\.package\](.*?)(?=\n\[|\Z)", workspace, re.S).group(1)
inherited = dict(re.findall(r'^(\w[\w-]*)\s*=\s*(.+)$', package, re.M))

def resolve(match):
    key = match.group(1)
    if key not in inherited:
        raise SystemExit(f"{key}.workspace has no [workspace.package] value")
    return f"{key} = {inherited[key]}"

crate = re.sub(r'^(\w[\w-]*)\.workspace\s*=\s*true$', resolve, crate, flags=re.M)
# `[lints] workspace = true` — drop the section header and its body.
crate = re.sub(r'\n\[lints\]\nworkspace = true\n', '\n', crate)

if '.workspace' in crate:
    raise SystemExit("unresolved workspace inheritance remains:\n" + crate)

open(crate_path, 'w').write(crate)
PY

cat > "$staging/SNAPSHOT.md" <<EOF
# Generated branch — do not commit here

This branch is a generated snapshot of \`crate/\` from the \`rmesh-minimal\`
development branch of this repository, published so that \`rmesh\` can take a
cargo git dependency without dragging in the \`occt/\` submodule (~900 MB).

Generated from: \`${SOURCE_REV}\` (\`${SOURCE_DESC}\`)
Regenerate with: \`scripts/make-rmesh-crate.sh\`

Edit \`crate/\` on \`rmesh-minimal\` and re-run the script; changes made directly
on this branch will be discarded.
EOF

git -C "$staging" init -q
git -C "$staging" add -A
git -C "$staging" -c user.name="$(git -C "$REPO" config user.name)" \
    -c user.email="$(git -C "$REPO" config user.email)" \
    commit -q -m "snapshot: the Rust crate alone, for cargo consumers

Generated by scripts/make-rmesh-crate.sh from ${SOURCE_REV}.
The occt/ submodule makes a git dependency on this repo cost ~900 MB
to resolve at zero features; this snapshot costs ~5 MB."

git -C "$REPO" fetch -q "$staging" HEAD
git -C "$REPO" branch -f "$BRANCH" FETCH_HEAD

echo "branch '$BRANCH' -> $(git -C "$REPO" rev-parse --short "$BRANCH")"
echo "  from     : $SOURCE_DESC"
echo "  files    : $(git -C "$REPO" ls-tree -r --name-only "$BRANCH" | wc -l)"
echo "  size     : $(git -C "$REPO" ls-tree -r -l "$BRANCH" | awk '{s+=$4} END {printf "%.1f MB\n", s/1048576}')"
echo
echo "next: git -C $REPO push origin $BRANCH"
